#!/usr/bin/env ruby
# vim: set filetype=ruby

require 'rubygems'
require 'bundler/setup'
require "thor"

class DotfilesCLI < Thor
  include Thor::Actions

  desc "install", "Creates symlinks in home directory"
  def install
    # install zsh / zprezto
    create_link "~/.zprezto", File.join(__dir__, "vendor/deps/prezto")
    Dir['.z*'].each {|p| create_link "~/#{p}", File.join(__dir__, p) }

    # install vim
    create_link "~/.vim", File.join(__dir__, ".vim")
  end

  desc "uninstall", "Removes symlinks in home directory"
  def uninstall
    say "uninstalling"
  end
end

DotfilesCLI.start(ARGV)
