#!/usr/bin/env ruby
# vim: set filetype=ruby

require 'rubygems'
require 'bundler/setup'
require "thor"

class DotfilesCLI < Thor
  include Thor::Actions

  desc "install", "Creates symlinks in home directory"
  def install
    Bundler.with_clean_env do
      case RUBY_PLATFORM
      when /linux/	      
      when /darwin/
	# TODO: install homebrew (if it doesnt exist)
	# TODO: ask homebrew which of these it has (install the oens that arent there)
	%w(cmake cscope ctags git git-extras lua luajit python rbenv rbenv-binstubs rbenv-gem-rehash the_silver_searcher tmux).each {|pkg| `brew install #{pkg}`}
	['macvim --with-cscope --with-lua --with-luajit --with-python --override-system-vim'].each {|pkg| `brew install #{pkg}`}
      end
    end

    # install zsh / zprezto
    create_link "~/.zprezto", File.join(__dir__, "vendor/deps/prezto")
    Dir['.z*'].each {|p| create_link "~/#{p}", File.join(__dir__, p) }

    # install vim
    create_link "~/.vim", File.join(__dir__, ".vim")
    create_link "~/.agignore", File.join(__dir__, ".agignore")

    # gemrc
    create_link "~/.gemrc", File.join(__dir__, ".gemrc")

    # git
    create_link "~/.gitignore", File.join(__dir__, ".gitignore")
  end

  desc "uninstall", "Removes symlinks in home directory"
  def uninstall
    say "uninstalling"
  end
end

DotfilesCLI.start(ARGV)
