#!/bin/bash
# vim: set filetype=bash

# Setup SSH Environment
if [ ! -L ~/.ssh ]; then
  echo 'Setup SSH environment'
  ln -fs ~/Dropbox/.ssh ~/.ssh
  chmod 700 ~/.ssh/id_rsa
fi

# Setup Homebrew
if [ ! -d /usr/local/Library ]; then
  echo 'Installing Homebrew'
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
fi

# Install Dependencies
packages=(bash-completion cmake curl ctags dnsmasq git git-extras libsass node python rbenv rbenv-binstubs rbenv-gem-rehash ruby-build the_silver_searcher wget)
for pkg in "${packages[@]}"; do
  if ! brew list -1 | grep -q "^${pkg}\$"; then
    echo "Installing Package '$pkg'"
    brew install $pkg
  fi
done

# Install MacVim
if [ ! -f /usr/local/bin/mvim ]; then
  echo "Installing Package 'macvim --with-python --override-system-vim'"
  brew install macvim --with-python --override-system-vim
  brew linkapps

  ln -fs $(pwd)/.vim /.vim
  git submodule init && git submodule update 
  brew unlink python
  (cd $(pwd)/.vim/bundle/YouCompleteMe && git submodule update && ./install.sh --clang-completer)
fi

# Setup dnsmasq
if [ ! -L /usr/local/etc/dnsmasq.conf ]; then
  echo "Linking /usr/local/etc/dnsmasq.conf'"
  ln -fs $(pwd)/etc/dnsmasq.conf /usr/local/etc/dnsmasq.conf

  # launch on start
  sudo cp $(brew list dnsmasq | grep /homebrew.mxcl.dnsmasq.plist$) /Library/LaunchDaemons/
  brew services start dnsmasq

  # add resolver for .dev TLD
  sudo mkdir -p /etc/resolver
  sudo ln -fs $(pwd)/etc/resolver/dev /etc/resolver/dev
fi

# Setup dotfiles
files=(.agignore .bash_profile .ctags .gemrc .gitconfig .gitignore .rbenv)
for file in "${files[@]}"; do
  if [ ! -L ~/$file ]; then
    echo "Linking ~/'$file'"
    ln -fs $(pwd)/$file ~/$file
  fi
done

source ~/.bash_profile
